---
- name: install postgres
  apt: pkg={{ item }} state=latest
  with_items:
  - postgresql-9.1
  - postgresql-server-dev-9.1
  - pgbouncer
  notify: restart postgresql

- name: update postgres auth config
  template: src=pg_hba.j2 dest=/etc/postgresql/9.1/main/pg_hba.conf
  notify: restart postgresql
