---
- name: add nginx repo key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: add nginx repo
  apt_repository: repo='deb http://nginx.org/packages/mainline/debian/ wheezy nginx' state=present

- name: uninstall any old nginx packages
  apt: pkg={{ item }} state=absent
  with_items:
  - nginx-extras
  - nginx-common

- name: create nginx servers directory
  file: dest=/etc/nginx/servers state=directory

- name: create nginx certificates directory
  file: path=/etc/nginx/certs state=directory

- name: startssl CA
  template: src=startssl.j2 dest=/etc/nginx/certs/startssl.pem

- name: install nginx
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
  - nginx
  notify: restart nginx

- name: replace nginx config
  template: src=nginx.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx
