---
- hosts: base
  vars_files:
  - vars.yml
  user: root
  tasks:
  - include: tasks/base.yml
- hosts: postgres
  vars_files:
  - vars.yml
  user: root
  tasks:
  - include: tasks/postgres.yml
- hosts: mariadb
  vars_files:
    - vars.yml
  user: root
  tasks:
  - include: tasks/mariadb.yml