---
# file: site.yml

- hosts: all
  user: root
  roles:
  - common

- hosts: django
  user: root
  roles:
  - nginx
  - python
  - uwsgi
  - node
  - django

- hosts: flask
  user: root
  roles:
  - nginx
  - python
  - uwsgi
  - flask

- hosts: cog4
  user: root
  roles:
  - nginx
  - python
  - uwsgi
  - mongodb
  - cog4

- hosts: cog4-www
  user: root
  roles:
  - nginx
  - cog4-www
  - mysql
  - wordpress
  - php-fpm

- hosts: cog4auth
  user: root
  roles:
  - java
  - maven
  - openconext

- hosts: postgres
  user: root
  roles:
  - postgresql
