---
# file: site.yml
- hosts: all
  user: root
  roles:
  - common

- hosts: django
  user: root
  roles:
  - nginx
  - python
  - uwsgi
  - django

- hosts: postgres
  user: root
  roles:
  - postgresql