---
# file: site.yml
- hosts: all
  user: root
  roles:
  - common

- hosts: djangoservers
  user: root
  roles:
  - nginx
  - python
  - uwsgi
  - django

- hosts: postgresservers
  user: root
  roles:
  - postgresql