---
# file: site.yml

- hosts: all
  user: root
  roles:
  - common

- hosts: django
  user: root
  roles:
  - nginx
  - python
  - uwsgi
  - node
  - django

- hosts: flask
  user: root
  roles:
  - nginx
  - python
  - uwsgi
  - flask

- hosts: cog4
  user: root
  roles:
  - nginx
  - python
  - uwsgi
  - flask
  - cog4

- hosts: postgres
  user: root
  roles:
  - postgresql
