---
# file: site.yml

- hosts: all
  user: root
  roles:
  - common

- hosts: django
  user: root
  roles:
  - nginx
  - python
  - uwsgi
  - node
  - django

- hosts: postgres
  user: root
  roles:
  - postgresql