---
- action: apt_key url='http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xCBCB082A1BB943DB' state=present
- action: apt_repository repo='deb http://mirror.netcologne.de/mariadb/repo/5.5/debian wheezy main'
- action: apt pkg={{ item }} state=present update_cache=yes
  with_items:
  - mariadb-server-5.5
  - libmariadbclient-dev
  - libmariadbd-dev
- action: service name=mysql state=restarted