---
- action: apt pkg={{ item }} state=present update_cache=yes
  with_items:
  - libmemcached-dev
  - memcached

- name: Memcached | Config file
  action: template src=templates/etc-memcached-conf.j2 dest=/etc/memcached.conf
  tags: memcached

- name: Memcached | PECL Library install
  action: shell printf "yes\n" | pecl install memcache creates=/usr/lib/php5/20090626/memcache.so
  tags: memcached

- name: Memcached | Config file for the PHP memcache extension
  action: template src=templates/etc-php5-conf-d-memcache-ini.j2 dest=/etc/php5/conf.d/memcache.ini
  tags: memcached
