---
- name: create directory for wordpress
  file: path={{ webapps_dir }}/{{ app_name }}/{{ instance_name }} state=directory

- name: download Wordpress
  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest={{ webapps_dir }}/{{ app_name }}/{{ instance_name }}/wordpress-{{ wp_version }}.tar.gz

- name: extract archive
  command: chdir={{ webapps_dir }}/{{ app_name }}/{{ instance_name }} /bin/tar xvf wordpress-{{ wp_version }}.tar.gz creates={{ webapps_dir }}/{{ app_name }}/{{ instance_name }} --strip-components=1

- name: Add group "wordpress"
  group: name=wordpress

- name: add user "wordpress"
  user: name=wordpress group=wordpress home={{ webapps_dir }}/{{ app_name }}/{{ instance_name }}

- name: fetch random salts for Wordpress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  sudo: no

- name: create Wordpress database
  mysql_db: name={{ wp_db_name }} state=present

- name: create Wordpress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present

- name: install some Wordpress plugins
  subversion: repo=http://svn.wp-plugins.org/{{ item.name }}/{{ item.version }}/ dest={{ webapps_dir }}/{{ app_name }}/{{ instance_name }}/wp-content/plugins/{{ item.name }}
  tags: wp_plugins
  with_items:
    - {name: all-in-one-favicon, version: trunk}
    - {name: better-wp-security, version: tags/3.6.5}
    - {name: bulk-move, version: tags/1.1.1}
    - {name: captain-typekit, version: trunk}
    - {name: disqus-comment-system, version: tags/2.74}
    - {name: embedded-video-with-link, version: tags/4.1}
    - {name: font-awesome, version: tags/3.1}
    - {name: google-analytics-for-wordpress, version: tags/4.3.5}
    - {name: intensedebate, version: tags/2.9.5}
    - {name: jetpack, version: tags/2.9.1}
    - {name: jquery-image-lazy-loading, version: tags/0.9}
    - {name: link-manager, version: trunk}
    - {name: mailchimp, version: tags/1.4.1}
    - {name: milestone, version: tags/1.0}
    - {name: nginx-compatibility, version: tags/0.2.5}
    - {name: order-categories, version: trunk}
    - {name: prev-next-keyboard-navigation, version: tags/0.6}
    - {name: rsvp, version: tags/1.7.0}
    - {name: social, version: tags/2.9.2}
    - {name: syntaxhighlighter, version: trunk}
    - {name: twitter-blackbird-pie, version: tags/0.5.3}
    - {name: unfiltered-mu, version: trunk}
    - {name: w3-total-cache, version: tags/0.9.3}
    - {name: wordpress-importer, version: tags/0.6.1}
    - {name: wordpress-mu-domain-mapping, version: tags/0.5.4.3}
    - {name: wordpress-popular-posts, version: tags/2.3.7}
    - {name: wordpress-seo, version: tags/1.5.2.2}
    - {name: wp-markdown, version: tags/1.4}
    - {name: wp-syntax, version: tags/1.0}
    - {name: wptouch, version: tags/3.1.9}
    - {name: segmentio, version: tags/0.5.6}
    #- {name: , version: }
    #- {name: stealth-login-page, version: tags/3.0.0}
    #- {name: limit-login-attempts, version: tags/1.7.1}

- name: copy Wordpress config file
  template: src=wp-config.php dest=/srv/wordpress/

- name: change ownership of Wordpress installation
  file: path={{ webapps_dir }}/{{ app_name }}/{{ instance_name }}/ owner=wordpress group=wordpress state=directory recurse=yes
