---
- name: install python 2.7
  apt: pkg=python2.7 state=latest

- name: install python development package
  apt: pkg=python2.7-dev state=latest

- name: install virtualenv and virtualenvwrapper
  apt: pkg={{ item }} state=latest
  with_items:
  - python-virtualenv
  - virtualenvwrapper
