---
- name: pull cog4 code from github
  git: repo={{ repo_url }} dest={{ webapps_dir }}/{{ app_name }}/{{ instance_name }}/src 

#- name: copy files to webdir
#  copy: src={{ webapps_dir }}/{{ app_name }}/{{ instance_name }}/src/ dest={{ webapps_dir }}/{{ app_name }}/{{ instance_name }}

# This is necessary because we need numpy installed first! Can this be fixed?
- name: upgrade the virtualenv.
  pip: requirements={{ webapps_dir }}/{{ app_name }}/{{ instance_name }}/src/requirements.txt virtualenv={{ webapps_dir }}/{{ app_name }}/{{ instance_name }}/.virtualenvs/{{ app_name }}/{{ instance_name }}

- name: Configure setup.sh
  template: src=setup.sh.j2 dest={{ webapps_dir }}/{{ app_name }}/{{ instance_name }}/setup.sh mode=0755

- name: install cog4 with dependencies
  command: "{{ webapps_dir }}/{{ app_name }}/{{ instance_name }}/setup.sh"

- name: create directory for log
  file: path=/var/log/cog4 state=directory owner=www-data group=www-data 
    
- name: make sure that the ansible_backup directory exsists
  file: path=/etc/nginx/servers/{{ app_name }} state=directory

- name: create nginx site config
  template: src=nginx_site.conf dest=/etc/nginx/servers/{{ app_name }}/{{ instance_name }}.conf
  notify:
    - restart nginx

- name: create directory for uwsgi
  file: path={{ webapps_dir }}/{{ app_name }}/{{ instance_name }} state=directory

- name: create uwsgi site config
  template: src=uwsgi_site.ini dest={{ webapps_dir }}/{{ app_name }}/{{ instance_name }}/uwsgi.ini 

- name: chown uwsgi fastrouter config to nobody
  file: path={{ webapps_dir }}/{{ app_name }}/{{ instance_name }}/uwsgi.ini owner=nobody group=nogroup
  notify:
    - restart uwsgi


